import { Router } from 'express';
import { authRoutes } from '../modules/auth/auth.routes';
import { registrationRoutes } from '../modules/registrations/registration.routes';
import { checkInRoutes } from '../modules/check-ins/check-in.routes';
import { screeningRoutes } from '../modules/screenings/screening.routes';
import { bloodBagRoutes } from '../modules/blood-bags/blood-bag.routes';
import { healthRoutes } from './health.routes';
export const apiRoutes = Router();
apiRoutes.use('/health', healthRoutes);
apiRoutes.use('/auth', authRoutes);
apiRoutes.use('/registrations', registrationRoutes);
apiRoutes.use('/registrations', checkInRoutes);
apiRoutes.use('/screenings', screeningRoutes);
apiRoutes.use(bloodBagRoutes);
